name: Test

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: "Update README.md"
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          # Ensure the repository is fetched with its history
          fetch-depth: 0

      - name: Set up environment variables
        run: |
          echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Update README.md
        run: |
          sed -i "s|https://img.shields.io/badge/Build_Latest-[0-9]\{8\}-blue?style=for-the-badge&logo=openwrt|https://img.shields.io/badge/Build_Latest-${DATE}-blue?style=for-the-badge&logo=openwrt|g" README.md

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Fetch the latest changes from the remote branch
          git pull origin main --rebase
          
          git add README.md
          git commit -m "Auto Update $(date +'%Y-%m-%d %H:%M:%S')"
          git push origin main
