#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description:   Build OpenWrt with Image Builder
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Build Test 1

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: true
        default: "openwrt:23.05.5"
        type: choice
        options:
          - openwrt:24.10.0-rc5
          - immortalwrt:24.10.0-rc3
          - immortalwrt:23.05.4
          - openwrt:23.05.5
      devices:
        description: "Select device target:"
        required: true
        default: "all"
        type: choice
        options:
          - all
          # Amlogic Devices
          - s905x
          - s905x2
          - s905x3
          - s905x4
          # Allwinner H5
          - h5-orangepi-zeroplus2
          - h5-orangepi-zeroplus
          - h5-orangepi-prime
          - h5-orangepi-pc2
          # Allwinner H6
          - h6-orangepi-lite2
          - h6-orangepi-1plus
          - h6-orangepi-3
          - h6-orangepi-3lts
          # Allwinner H616/H618
          - h616-orangepi-zero2
          - h618-orangepi-zero2w
          - h618-orangepi-zero3
          # Rockchip
          - rk3566-orangepi-3b
          - rk3588-orangepi-5plus
          - rk3588s-orangepi-5
          # x86
          - x86-64
      prerelease:
        description: "Pre-release:"
        required: true
        default: "false"
        type: choice
        options:
          - "true"
          - "false"
      notiftele:
        description: "Notif To Telegram:"
        required: true
        default: "true"
        type: choice
        options:
          - "true"
          - "false"

env:
  TZ: Asia/Jakarta
  IMAGEBUILDER_SH: imagebuilder.sh
  DEBIAN_FRONTEND: noninteractive
  PYTHON_PACKAGES: "telethon colorama"
  APT_PACKAGES: >-
    build-essential libncurses5-dev libncursesw5-dev zlib1g-dev gawk git
    gettext libssl-dev xsltproc rsync wget unzip tar gzip qemu-utils
    mkisofs jq python3 python3-pip

jobs:
  prebuild:
    runs-on: ubuntu-latest
    name: ${{ inputs.releases_branch }}
    outputs:
      devices: ${{ steps.set-matrix.outputs.devices }}
    steps:
      - name: Set Matrix Run
        id: set-matrix
        run: |
          if [ "${{ inputs.devices }}" == "all" ]; then
            DEVICES_LIST='["s905x","s905x2","s905x3","s905x4","h5-orangepi-zeroplus2","h5-orangepi-zeroplus","h5-orangepi-prime","h5-orangepi-pc2","h6-orangepi-lite2","h6-orangepi-1plus","h6-orangepi-3","h6-orangepi-3lts","h616-orangepi-zero2","h618-orangepi-zero2w","h618-orangepi-zero3","rk3566-orangepi-3b","rk3588-orangepi-5plus","rk3588s-orangepi-5","x86-64"]'
          else
            DEVICES_LIST="[\"${{ inputs.devices }}\"]"
          fi
          echo "devices=$DEVICES_LIST" >> $GITHUB_OUTPUT

  build:
    needs: prebuild
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    name: "${{ matrix.devices }}"
    strategy:
      fail-fast: false
      matrix:
        devices: ${{fromJSON(needs.prebuild.outputs.devices)}}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Required Packages
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install ${{ env.APT_PACKAGES }}
          pip install ${{ env.PYTHON_PACKAGES }}

      - name: Initialize Environment
        run: |
          sudo timedatectl set-timezone "$TZ"
          RELEASE_BRANCH="${{ inputs.releases_branch }}"
          RELEASE_TAG="${RELEASE_BRANCH/:/_}"
          echo "RELEASE_BRANCH=${RELEASE_BRANCH}" >> $GITHUB_ENV
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "DEVICES=${{ matrix.devices }}" >> $GITHUB_ENV
          echo "DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV
          echo -e "[\033[94m INFO \033[0m] Building for device: ${{ matrix.devices }}"

      - name: Build Image and Rootfs
        id: imagebuilder
        run: |
          echo -e "[\033[95m STEPS \033[0m] Starting firmware and rootfs build"
          chmod +x ${IMAGEBUILDER_SH}
          if bash ${IMAGEBUILDER_SH} ${{ env.RELEASE_BRANCH }} "${{ env.DEVICES }}"; then
            echo "status=success" >> $GITHUB_OUTPUT
            echo -e "[\033[92m SUCCESS \033[0m] Build completed successfully"
          else
            echo "status=failed" >> $GITHUB_OUTPUT
            echo -e "[\033[91m ERROR \033[0m] Build failed"
            exit 1
          fi

      - name: Clean Build Space
        if: ${{ steps.imagebuilder.outputs.status == 'success' && !cancelled() }}
        run: |
          cd imagebuilder
          sudo find . -mindepth 1 -not -path './out_firmware*' -delete
          df -hT ${PWD}

      - name: Upload to Artifacts
        if: ${{ steps.imagebuilder.outputs.status == 'success' }}
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ env.DEVICES }}
          path: imagebuilder/out_firmware/*.img.gz
          retention-days: 7

      - name: Upload to Release
        if: ${{ steps.imagebuilder.outputs.status == 'success' }}
        uses: svenstaro/upload-release-action@v2
        continue-on-error: false
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: imagebuilder/out_firmware/*.img.gz
          tag: ${{ env.RELEASE_TAG }}-${{ env.DATE }}
          release_name: RTA-WRT - ${{ env.RELEASE_TAG }}-${{ env.DATE }}
          overwrite: true
          prerelease: ${{ inputs.prerelease }}
          body: |
            ![GitHub Downloads](https://img.shields.io/github/downloads/rizkikotet-dev/RTA-WRT/${{ env.RELEASE_TAG }}-${{ env.DATE }}/total?style=for-the-badge&logo=Openwrt)
            ### RTA-WRT ${{ env.BASE }}-${{ env.BRANCH }} Image Information

            ${{ steps.changelog.outputs.CHANGELOG }}

            See [here](https://github.com/rizkikotet-dev/RTA-WRT?tab=readme-ov-file#detail-firmware) for detailed features and information.
            
            Default Settings:
            - IP Address: 192.168.1.1
            - Username: root
            - Password: rtawrt
            - WIFI SSID: RTAWRT_2g | RTAWRT_5g (if supported)

  notify:
    needs: build
    runs-on: ubuntu-latest
    if: ${{ inputs.notiftele == 'true' }}
    name: Notify Telegram
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: downloaded-firmware

      - name: Setup Environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install ${{ env.APT_PACKAGES }}
          pip install ${{ env.PYTHON_PACKAGES }}
          sudo timedatectl set-timezone "$TZ"

      - name: Generate Changelog
        id: changelog
        run: |
          changelog=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' CHANGELOG.md)
          changelog="${changelog//'%'/'%25'}"
          changelog="${changelog//$'\n'/'%0A'}"
          changelog="${changelog//$'\r'/'%0D'}"
          echo "CHANGELOG=$changelog" >> $GITHUB_OUTPUT

      - name: Send Telegram Notification
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: 36
        run: |
          DATE=$(date +'%d%m%Y')
          DATE2=$(date +'%d\-%m\-%Y')
          TAG="${{ env.RELEASES_TAG }}-${DATE}"
          NEWTAG=$(echo "$TAG" | sed -E 's/([_\-\.\[\]()])/\\\1/g')
          
          MESSAGE="▬▬▬▬▬▬▬▬▬▬▬▬▬▬\n                          NEW UPDATE\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬\nNAME   : 🔔 RTA\-WRT OpenWRT\nTAG       : ${NEWTAG}\nDATE     : ${DATE2}\nREPO    : rizkikotet\-dev/RTA\-WRT\n▬▬▬▬▬▬▬▬▬▬▬▬▬▬"
          
          BUTTONS='{
              "inline_keyboard": [
                  [{"text": "KLIK DISINI", "url": "https://github.com/rizkikotet-dev/RTA-WRT"}]
              ]
          }'
          
          curl -s -X POST "https://api.telegram.org/bot${BOT_TOKEN}/sendMessage" \
            -d "chat_id=${GROUP_ID}" \
            -d "text=${MESSAGE}" \
            -d "parse_mode=MarkdownV2" \
            -d "reply_markup=$(echo $BUTTONS | jq -c .)" \
            -d "message_thread_id=${MESSAGE_THREAD_ID}"


      # - name: Upload To Telegram
      #   env:
      #     API_ID: ${{ secrets.API_ID }}
      #     API_HASH: ${{ secrets.API_HASH }}
      #     BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      #     GROUP_ID: ${{ secrets.CHAT_ID }}
      #     MESSAGE_THREAD_ID: 124
      #   run: |
      #     cd ${PWD}
      #     ls -l downloaded-firmware
      #     chmod +x telebot.py
      #     DATE=$(date +'%d%m%Y')
      #     MESSAGE=$(cat <<-END
      #     <blockquote>🟢 NEW UPDATE AVAILABLE 🟢</blockquote>

      #     <blockquote>➣ Name: RTA-WRT</blockquote>
      #     <blockquote>➣ Tag: ${OPENWRT_BASE}_${OPENWRT_BRANCH}-$DATE</blockquote>
      #     <blockquote>➣ Date : $DATE</blockquote>

      #     <pre>${{ steps.changelog.outputs.CHANGELOG }}</pre>
      #     END
      #     )
      #     if [ "${{ inputs.notiftele }}" == "true" ]; then
      #       python3 telebot.py "$API_ID" "$API_HASH" "$BOT_TOKEN" "$MESSAGE" "$GROUP_ID" "$MESSAGE_THREAD_ID" "downloaded-firmware/*/*.img.gz"
      #     fi