#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description:   Build OpenWrt with Image Builder
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "openwrt:23.05.5"
        type: choice
        options:
          - immortalwrt:23.05.4
          - openwrt:23.05.5

env:
  TZ: Asia/Jakarta
  IMAGEBUILDER_SH: imagebuilder.sh

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Telegram
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Env
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install jq

      - name: Add changelog info to new release description
        id: changelog
        shell: bash
        run: |
          r=$(awk '/^\*\*Changelog\*\*/ {if(found) exit; found=1} found' ${PWD}/CHANGELOG.md)
          r="${r//'%'/'%25'}"
          r="${r//$'\n'/'%0A'}"
          r="${r//$'\r'/'%0D'}"
          formatted_changelog=$(echo -e "$r" | sed 's/%0A/\n/g')
          echo "CHANGELOG=$formatted_changelog" >> $GITHUB_OUTPUT 

      - name: Notify Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: 36
        run: |
          DATE=$(date +"%Y-%m-%d %H:%M:%S")
          RELEASES_BRANCH="${{ inputs.releases_branch }}"${RELEASES_BRANCH%:*}
          RELEASES_TAG=${RELEASES_BRANCH/:/_}
          MESSAGE="
          ╔════════════════════╗\n\
          ║ NEW UPDATE AVAILABLE ║\n\
          ╚════════════════════╝\n\
          ➣ Name: RTA-WRT\n\
          ➣ Tag: $RELEASES_TAG-$DATE\n\
          ➣ Date : $DATE\n\
          \n\
          ${{ steps.changelog.outputs.CHANGELOG }}"

          BUTTONS='{
            "inline_keyboard": [
              [
                {"text": "KLIK DISINI", "url": "https://github.com/rtaserver/RTA-WRT"}
              ]
            ]
          }'

          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
              -d "chat_id=$GROUP_ID" \
              -d "text=$MESSAGE" \
              -d "parse_mode=MarkdownV2" \  # Use MarkdownV2 for formatting
              -d "reply_markup=$(echo $BUTTONS | jq -c .)" \
              -d "message_thread_id=$MESSAGE_THREAD_ID"  # Remove this line if you don't want to use threads