#=====================================================================================
# https://github.com/ophub/amlogic-s9xxx-openwrt
# Description:   Build OpenWrt with Image Builder
# Instructions:  https://openwrt.org/docs/guide-user/additional-software/imagebuilder
# Download from: https://downloads.openwrt.org/releases
#                https://downloads.immortalwrt.org/releases
#=====================================================================================

name: Test

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      releases_branch:
        description: "Select the releases branch"
        required: false
        default: "openwrt:23.05.5"
        type: choice
        options:
          - immortalwrt:23.05.4
          - openwrt:23.05.5

env:
  TZ: Asia/Jakarta
  IMAGEBUILDER_SH: imagebuilder.sh

jobs:
  notify:
    runs-on: ubuntu-latest
    name: Notify Telegram
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update Env
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install jq
          sudo timedatectl set-timezone "$TZ"

      - name: Notify Telegram
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GROUP_ID: ${{ secrets.CHAT_ID }}
          MESSAGE_THREAD_ID: 36
        run: |
          DATE=$(date +'%Y%m%d')
          RELEASES_BRANCH="${{ inputs.releases_branch }}"
          RELEASES_TAG="${RELEASES_BRANCH/:/_}"
          MESSAGE="\
            *NEW UPDATE*

            >Name: RTA-WRT
            >Tag: $RELEASES_TAG
            >Release Date: $DATE"

          BUTTONS='{
            "inline_keyboard": [
              [
                {"text": "KLIK DISINI", "url": "https://github.com/rtaserver/RTA-WRT"}
              ]
            ]
          }'

          curl -s -X POST "https://api.telegram.org/bot$BOT_TOKEN/sendMessage" \
              -d "chat_id=$GROUP_ID" \
              -d "text=$MESSAGE" \
              -d "parse_mode=MarkdownV2" \
              -d "reply_markup=$(echo $BUTTONS | jq -c .)" \
              -d "message_thread_id=$MESSAGE_THREAD_ID"